# Generated by Django 5.2.7 on 2026-01-26 20:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_batch_product_alter_stock_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код группы')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('KIP', 'КИПиА'), ('CHEM', 'Химреагенты'), ('PIPE', 'Трубопродукция'), ('ZIP', 'ЗИП'), ('PPE', 'СИЗ'), ('FUEL', 'ГСМ'), ('EQUIP', 'Оборудование')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа материалов',
                'verbose_name_plural': 'Группы материалов',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код объекта')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('object_type', models.CharField(choices=[('OILFIELD', 'Месторождение'), ('WORKSHOP', 'Цех переработки'), ('WELL', 'Скважина'), ('DRILL', 'Буровая установка'), ('WAREHOUSE', 'Промежуточный склад')], max_length=20, verbose_name='Тип объекта')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Участок/Месторождение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Объект потребления',
                'verbose_name_plural': 'Объекты потребления',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='batch',
            name='cert_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер сертификата соответствия'),
        ),
        migrations.AddField(
            model_name='batch',
            name='cert_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Сертификат действителен до'),
        ),
        migrations.AddField(
            model_name='batch',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AddField(
            model_name='batch',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier_lot',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер партии поставщика'),
        ),
        migrations.AddField(
            model_name='location',
            name='storage_conditions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Условия хранения'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='abc_class',
            field=models.CharField(choices=[('A', 'A - Критически важные (80% стоимости)'), ('B', 'B - Средней важности (15% стоимости)'), ('C', 'C - Малоценные (5% стоимости)')], default='C', max_length=1, verbose_name='ABC-класс'),
        ),
        migrations.AddField(
            model_name='product',
            name='critical_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-5, где 5 - критически важно для бурения/добычи (остановка)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень критичности'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_oilfield_specific',
            field=models.BooleanField(default=False, help_text='Требует сертификации для применения на объектах добычи', verbose_name='Спец. для добычи'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Срок поставки (дней)'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=0, help_text='При достижении этого остатка формируется заявка на закупку', max_digits=12, verbose_name='Точка заказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Страховой запас'),
        ),
        migrations.AddField(
            model_name='product',
            name='tnvd_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код ТНВЭД'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Поставщик прошел аккредитацию Татнефти', verbose_name='Аккредитован'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='lot_number',
            field=models.CharField(max_length=50, verbose_name='Номер партии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Макс. запас'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Мин. запас (критический)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier', verbose_name='Основной поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('EA', 'шт'), ('KG', 'кг'), ('L', 'л'), ('M', 'м'), ('TON', 'т'), ('M3', 'м³')], default='EA', max_length=3, verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='warehouse.product', verbose_name='Товар'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('product', 'lot_number')},
        ),
        migrations.AddField(
            model_name='product',
            name='material_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.materialgroup', verbose_name='Группа материалов'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Зарезервировано')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата резерва')),
                ('planned_date', models.DateField(verbose_name='Плановая дата отгрузки')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активно'), ('SHIPPED', 'Отгружено'), ('CANCELLED', 'Отменено')], default='ACTIVE', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.batch', verbose_name='Партия')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.object', verbose_name='Объект назначения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.product', verbose_name='Товар')),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем зарезервировано')),
            ],
            options={
                'verbose_name': 'Резерв под объект',
                'verbose_name_plural': 'Резервы под объекты',
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('required_date', models.DateField(verbose_name='Требуемая дата поставки')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('NORMAL', 'Нормальный'), ('HIGH', 'Высокий'), ('CRITICAL', 'Критический (остановка)')], default='NORMAL', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('APPROVED', 'Утверждено'), ('IN_WORK', 'В работе'), ('PARTIAL', 'Частично выполнено'), ('COMPLETED', 'Выполнено'), ('CANCELLED', 'Отменено')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Основание/Примечание')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.object', verbose_name='Объект потребления')),
            ],
            options={
                'verbose_name': 'Заявка на снабжение',
                'verbose_name_plural': 'Заявки на снабжение',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='picktask',
            name='supply_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_tasks', to='warehouse.supplyrequest', verbose_name='По заявке'),
        ),
        migrations.CreateModel(
            name='SupplyRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Запрошено')),
                ('quantity_issued', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Отпущено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product', verbose_name='Товар')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.supplyrequest')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявок',
            },
        ),
    ]
