# Generated by Django 5.2.7 on 2026-01-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_materialgroup_object_alter_product_options_and_more'),
    ]

    operations = [
    ]
