# Generated by Django 5.2.7 on 2026-01-26 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20260126_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон контакта'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Скважина, цех, НГДУ, куст, проезд', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Время доставки, ориентиры, особые условия', verbose_name='Примечание по доставке'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.object', verbose_name='Объект из справочника (если есть)'),
        ),
    ]
