# Generated by Django 5.2.7 on 2026-01-26 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_supplyrequest_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequest',
            name='contact_person',
            field=models.CharField(blank=True, help_text='ФИО получателя на объекте', max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Мобильный телефон для связи', max_length=50, verbose_name='Телефон контакта'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Например: скв. №45, куст 12, НГДУ Азнакаево, въезд с трассы М7', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Время доставки, ориентиры, проезд, координаты', verbose_name='Примечание по доставке'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='object',
            field=models.ForeignKey(blank=True, help_text='Выберите из списка или заполните адрес вручную ниже', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.object', verbose_name='Объект (из справочника)'),
        ),
    ]
