# Generated by Django 5.2.7 on 2026-01-28 14:24

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_supplyrequest_contact_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('APPROVED', 'Утверждено'), ('IN_WORK', 'В работе'), ('PARTIAL', 'Частично выполнено'), ('COMPLETED', 'Выполнено'), ('CANCELLED', 'Отменено')], db_index=True, default='DRAFT', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'location'], name='warehouse_s_product_6ea59e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['status', '-created_at'], name='warehouse_s_status_eaebbe_idx'),
        ),
    ]
