# Generated by Django 5.2.7 on 2026-01-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_product_sku_alter_stockmove_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='picktask',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.batch', verbose_name='Партия'),
        ),
        migrations.AddIndex(
            model_name='picktask',
            index=models.Index(fields=['is_done', 'created_at'], name='warehouse_p_is_done_76631f_idx'),
        ),
        migrations.AddIndex(
            model_name='picktask',
            index=models.Index(fields=['supply_request', 'is_done'], name='warehouse_p_supply__0a1d24_idx'),
        ),
        migrations.AddIndex(
            model_name='picktask',
            index=models.Index(fields=['from_location', 'is_done'], name='warehouse_p_from_lo_f00fec_idx'),
        ),
        migrations.AddIndex(
            model_name='picktask',
            index=models.Index(fields=['product', 'batch'], name='warehouse_p_product_cf3568_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['location', 'product'], name='warehouse_s_locatio_d28585_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['batch', 'product'], name='warehouse_s_batch_i_dea1da_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequestitem',
            index=models.Index(fields=['request', 'product'], name='warehouse_s_request_1ebc54_idx'),
        ),
    ]
