# Generated by Django 5.2.7 on 2026-01-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_picktask_batch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplyrequestitem',
            unique_together={('request', 'product')},
        ),
    ]
