# Generated by Django 5.2.7 on 2026-02-26 13:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0009_alter_supplyrequestitem_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="Использовать эту цену по умолчанию при заказе",
                        verbose_name="Предпочтительная цена",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Действует с"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="warehouse.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="warehouse.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена товара",
                "verbose_name_plural": "История цен товаров",
                "ordering": ["-valid_from", "price"],
                "indexes": [
                    models.Index(
                        fields=["product", "supplier", "-valid_from"],
                        name="warehouse_p_product_8dcf6f_idx",
                    ),
                    models.Index(
                        fields=["product", "is_preferred"],
                        name="warehouse_p_product_4469ea_idx",
                    ),
                ],
            },
        ),
    ]
