# Generated by Django 5.2.7 on 2026-02-27 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0010_productprice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="stock",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_levels",
                to="warehouse.location",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["product", "status"], name="warehouse_r_product_469035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["object", "status"], name="warehouse_r_object__f598b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["planned_date"], name="warehouse_r_planned_db37b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["quantity"], name="warehouse_s_quantit_67489e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplyrequest",
            index=models.Index(
                fields=["required_date"], name="warehouse_s_require_dc0f05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplyrequest",
            index=models.Index(
                fields=["priority", "status"], name="warehouse_s_priorit_ce527e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("product", "location", "batch"),
                name="unique_stock_per_product_location_batch",
            ),
        ),
    ]
