# Generated by Django 5.2.12 on 2026-04-06 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_reservation_supply_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reservation',
            new_name='warehouse_r_supply__34cd63_idx',
            old_name='warehouse_r_supply__status_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='warehouse_r_supply__ca0054_idx',
            old_name='warehouse_r_supply__prod_stat_idx',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receipt_applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Приход проведён'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Получен в системе'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Принял'),
        ),
    ]
